# Generated by Django 3.2 on 2021-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210913_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='mark',
            new_name='mark1',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='namp',
            new_name='mark2',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='ville',
            new_name='mark3',
        ),
        migrations.AddField(
            model_name='todo',
            name='mark4',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='mark5',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='mark6',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='mark7',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='mark8',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='namp1',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='namp2',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='namp3',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='namp4',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='namp5',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='namp6',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='namp7',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='namp8',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='ville1',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='ville2',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='ville3',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
